baseURL = "https://frai.dev/"
languageCode = "en-us"
title = "Frai"
theme = "m10c"
paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

[params]
  avatar = "https://avatars.githubusercontent.com/u/25258368?v=4"
  author = "Frai"
  description = "Fullstack developer and Computer Engineering."
  menu_item_separator = " - "
  favicon = "/favicon.ico"


[[params.social]]
  icon = "github"
  name = "My Github"
  url = "https://github.com/fraidev"

[[params.social]]
  icon = "twitter"
  name = "Twitter"
  url = "https://twitter.com/fraidev"


[params.style]
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#219fd5"